<?php 
session_start();
include 'pub/scripts/load.php';
?>
<html>
<head>
	<meta charset="utf-8"> 
	<meta name="description" content="Convert your long url into a sub 10 character link.">
	<meta name="keywords" content="url, shortener, link">
	<meta name="robots" content="index,follow">
	<meta content = "Convert your long url into a sub 10 character link." name="Description">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Url Shortener</title>
	<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script><![endif]-->
	<link rel="shortcut icon" href="/pub/images/favicon.ico" type="image/x-icon">
	<link rel="icon" href="/pub/images/favicon.ico" type="image/x-icon">
	<link rel='stylesheet' href='pub/style/style.css'/>
</head>
<body>
	<header class="grid-fluid blue-bg">
		<div class="row">
			<div class="banner-text center">
				Made by <a class="banner-link" href="http://davidyoung.tech">davidyoung.tech</a>
			</div>
		</div>
	</header> <!-- Header -->
	<main class="grid-container">
		<div class="row hero-row">
			<h2 class="center">
				Shorten a Link in a single click
			</h2>
			<h3 class="center">
				And quite possibly get back something shorter.
			</h3>
		</div>
		<div class="row hero-row center">
			<form id="form">
				<input id="input-box" type="text" name="searching" maxlength="124" placeholder="Link to shorten">
				<div class="col-4 offset-4">
					<input id="submit-btn" type="submit" id="lets-go" value="Make it happen.">
				</div>
			</form>
		</div>
	</main> <!-- Row -->
	<footer class="row">
		<p class="copyright center">
			This website is not affiliated with any sites linked to by URLS generated by this site.
		</p>
		<p class="copyright center">
			<a href="https://github.com/deedubwhy/url-short-php">View the source</a>
		</p>
	</footer> <!-- Row -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="pub/js/app.js"></script>
</body>
</html>