<?php include 'pub/scripts/pageload.php';?>
<html>
<head>
	<!--Looking at the source code I see, thanks for being so interested!-->
	<meta charset="utf-8"> 
	<meta name="description" content="Convert your long url into a sub 10 character link.">
	<meta name="keywords" content="url, shortener">
	<meta name="robots" content="index,follow">
	<meta content = "Convert your long url into a sub 10 character link." name="Description">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>dwy shorty</title>
	<link rel='stylesheet' href='pub/style/style.css'/>
</head>
<body>
	<div class="grid-fluid">
		<div class="row blue-bg">
			<div class="banner-text center">
				Made by <a class="banner-link" href="https://davidyoung.tech">www.davidyoung.tech</a>
			</div>
		</div>
		<div class="grid-container">
			<div class="row hero-row">
				<h2 class="center">
					Shorten a Link in a single click
				</h2>
				<h3 class="center">
					Guaranteed to be the best short link you ever saw.
				</h3>
			</div>
			<div class="row hero-row center">
				<input type="text" name="searching" maxlength="124" placeholder="Link to shorten">
				<div class="col-4 offset-4">
					<button id="lets-go">Make it happen</button>
				</div>
			</div>
			<div class="row">
				<p class="copyright center">
					This website is not affiliated with any sites linked to by URLS generated by this site.
				</p>
				<p class="copyright center">
					<a href="https://github.com/deedubwhy/url-short-php">View the source</a>
				</p>
			</div>
		</div>
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="pub/js/main.js"></script>
</body>
</html>