import React from "react";
import styled from "@emotion/styled";

// our components
import Type from "@/components/Type";
import Link from "@/components/Link";
import { GridContainer } from "@/layout/Grid";
import Row from "@/layout/Row";
import Alignment from "@/layout/Alignment";

const CopyrightType = styled(Type)`
    color: #FFF;
    font-size: 12px;
`;

const FooterContainer = GridContainer.withComponent("footer");

const Footer = (): JSX.Element => {
    return (
        <FooterContainer>
            <Row>
                <Alignment
                    alignment={"center"}>
                    <CopyrightType
                        element="p">
                        This website is not affiliated with any sites linked to by URLS generated by this site.
                    </CopyrightType>
                    <Link
                        destination="https://github.com/dayvidwhy/shortest">
                        <CopyrightType
                            element="span">
                            View the source
                        </CopyrightType>
                    </Link>
                </Alignment>
            </Row>
        </FooterContainer>
    );
};

export default Footer;
