import React from "react";

const Footer = () => {
    return (
        <footer className="row">
            <p className="copyright center">
                This website is not affiliated with any sites linked to by URLS generated by this site.
            </p>
            <p className="copyright center">
                <a href="https://github.com/dayvidwhy/shortest">View the source</a>
            </p>
        </footer>
    );
};

export default Footer;
