import React from "react";
import Type from "@/components/Type.js";
import Link from "@/components/Link.js";

const Footer = () => {
    return (
        <footer className="grid-container">
            <div className="row center">
                <Type className="copyright" element="p">
                    This website is not affiliated with any sites linked to by URLS generated by this site.
                </Type>
                <Link
                    destination="https://github.com/dayvidwhy/shortest">
                    <Type className="copyright" element="span">
                        View the source
                    </Type>
                </Link>
            </div>
        </footer>
    );
};

export default Footer;
